services:
  - type: web
    name: football-predictions-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://football-predictions.onrender.com
    healthCheckPath: /health
    autoDeploy: true 